apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-db-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd-storage-typo-wrong
  resources:
    requests:
      storage: 10Gi
